### ISSUE TITLE
omm

### ISSUE THREAD

**Issue by SillyDreamer** [wavesplatform/WavesSDK-android#13]
dApp = "3N5MStpzr7huB376SNGpMGCMKet8JmwF42e"
feeAssetId = ""
payment = {ArrayList@12527}  size = 0
chainId = 84
fee = 100000
proofs = {ArrayList@12528}  size = 0
senderPublicKey = "FaN2AKbGozusK5LYgW53sn1ApfmPcQFuJgPXdG9wF3Mb"
signature = null
timestamp = 1567941705907
type = 16
version = 1
shadow$_klass_ = {Class@11095} "class com.wavesplatform.sdk.model.request.node.InvokeScriptTransaction"
shadow$_monitor_ = 0

**Comment by SillyDreamer** [comment]
toBytes() = {byte[83]@12606} 
 0 = 16
 1 = 1
 2 = 84
 3 = -40
 4 = -113
 5 = -115
 6 = 19
 7 = 10
 8 = -76
 9 = -30
 10 = -49
 11 = -34
 12 = 45
 13 = 25
 14 = -20
 15 = 96
 16 = 72
 17 = 83
 18 = 92
 19 = -106
 20 = -55
 21 = -3
 22 = -17
 23 = 38
 24 = -114
 25 = -11
 26 = 47
 27 = -71
 28 = -112
 29 = 92
 30 = 74
 31 = 75
 32 = -32
 33 = 113
 34 = 66
 35 = 1
 36 = 84
 37 = -87
 38 = 85
 39 = -22
 40 = 70
 41 = -124
 42 = 42
 43 = -2
 44 = -45
 45 = -35
 46 = -58
 47 = 100
 48 = -72
 49 = 99
 50 = 5
 51 = 19
 52 = -113
 53 = 38
 54 = -98
 55 = 123
 56 = 11
 57 = 101
 58 = -14
 59 = -81
 60 = -101
 61 = 0
 62 = 0
 63 = 0
 64 = 0
 65 = 0
 66 = 0
 67 = 0
 68 = 0
 69 = 0
 70 = 0
 71 = 1
 72 = -122
 73 = -96
 74 = 0
 75 = 0
 76 = 0
 77 = 1
 78 = 109
 79 = 16
 80 = -101
 81 = -64
 82 = -77

**Comment by SillyDreamer** [comment]
var byt = WavesCrypto.base58decode("FaN2AKbGozusK5LYgW53sn1ApfmPcQFuJgPXdG9wF3Mb")

**Comment by SillyDreamer** [comment]
var byt = WavesCrypto.base58decode("FaN2AKbGozusK5LYgW53sn1ApfmPcQFuJgPXdG9wF3Mb")0 = -40
1 = -113
2 = -115
3 = 19
4 = 10
5 = -76
6 = -30
7 = -49
8 = -34
9 = 45
10 = 25
11 = -20
12 = 96
13 = 72
14 = 83
15 = 92
16 = -106
17 = -55
18 = -3
19 = -17
20 = 38
21 = -114
22 = -11
23 = 47
24 = -71
25 = -112
26 = 92
27 = 74
28 = 75
29 = -32
30 = 113
31 = 66

**Comment by mefilt** [comment]
val args = mutableListOf(
            InvokeScriptTransaction.Arg("string", "Some string!"),
            InvokeScriptTransaction.Arg("integer", 128L),
            InvokeScriptTransaction.Arg("integer", -127L),
            InvokeScriptTransaction.Arg("boolean", true),
            InvokeScriptTransaction.Arg("boolean", false),
            InvokeScriptTransaction.Arg("binary", "base64:VGVzdA=="))

        val call = InvokeScriptTransaction.Call(
            function = "testarg",
            args = args
        )

        val payment = mutableListOf(
            InvokeScriptTransaction.Payment(
                assetId = null,
                amount = 1L))

        val transaction = InvokeScriptTransaction(
            dApp = "3Mv9XDntij4ZRE1XiNZed6J74rncBpiYNDV",
            call = call,
            payment = payment)

        transaction.fee = 500000L
        transaction.sign(SEED)

        WavesSdk.service()
            .getNode()
            .transactionsBroadcast(transaction)
            .compose(RxUtil.applyObservableDefaultSchedulers())
            .subscribe({
                Assert.assertEquals(true, true)
            }, {
                Assert.assertEquals(true, false)
            })
